services:    
  web:
    build: ./services/web
    command: ""
    env_file:
      - ./.env.dev
    volumes:
      - ./services/web:/usr/src/app/
    ports:
      - "5001:5000"
    depends_on:
      - db
      - redis

  worker:
    build: ./services/web
    command: celery -A project.celery_app.celery worker --loglevel=info --concurrency=4
    volumes:
      - ./services/web:/usr/src/app/
    depends_on:
      - db
      - redis

  db:
    image: postgres:18
    container_name: postgres18
    environment:
      POSTGRES_USER: hello_flask
      POSTGRES_PASSWORD: hello_flask
      POSTGRES_DB: hello_flask_dev
    volumes:
    - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
  redis:
    image: redis:7

volumes:
  pgdata: