services:
  db:
    image: postgres:18
    container_name: postgres18
    environment:
      POSTGRES_USER: hello_flask
      POSTGRES_PASSWORD: hello_flask
      POSTGRES_DB: hello_flask_dev
    volumes:
    - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
      
  web:
    build: ./services/web
    env_file:
      - ./.env.dev
    volumes:
      - ./services/web:/usr/src/app/
    ports:
      - "5001:5000"
    depends_on:
      - db

volumes:
  pgdata: